id: P009467
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 19:40:09.643895
source_metadata:
  id: bdr:W4CZ15584
  title: བེའུ་བུམ་ཡིད་བཞིན་ནོར་བུ།
  author: ''
  volumes:
    d97ac637114946b1b56f2b3a7d44f1ea:
      image_group_id: I1KG12911
      title: ''
      volume_number: 1
      total_pages: 68
  access: http://purl.bdrc.io/admindata/AccessRestrictedSealed
  restrictedInChina: false
