id: I49084F03
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T13:38:07+00:00'
last_modified: '2022-06-08T11:14:59.481429+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ15584
  title: བེའུ་བུམ་ཡིད་བཞིན་ནོར་བུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedSealed
  restrictedInChina: false
  base:
    EE1E:
      image_group_id: I1KG12911
      title: ''
      total_pages: 68
      order: 1
      base_file: EE1E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
